name: Docker

on:
  push:
    branches:
      - master

jobs:
  push:
    name: Push
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false

      matrix:
        image:
          - {type: "games", image: "fivem"       , PREFIX: "", SUFFIX: "", context: "./games/fivem"}
          - {type: "games", image: "satisfactory", PREFIX: "", SUFFIX: "", context: "./games/satisfactory"}
          - {type: "games", image: "source"      , PREFIX: "", SUFFIX: "", context: "./games/source"}

          - {type: "generic", image: "alpine", PREFIX: "", SUFFIX: "", context: "./generic/alpine"}

          - {type: "go", image: "1.14", PREFIX: "go", SUFFIX: "", context: "./go"}
          - {type: "go", image: "1.15", PREFIX: "go", SUFFIX: "", context: "./go"}
          - {type: "go", image: "1.16", PREFIX: "go", SUFFIX: "", context: "./go"}

          - {type: "installers", image: "alpine", PREFIX: "", SUFFIX: "-install", context: "./installers/alpine"}
          - {type: "installers", image: "source", PREFIX: "", SUFFIX: "-install", context: "./installers/source"}

          - {type: "java", image: "8" , PREFIX: "java", SUFFIX: "", context: "./java"}
          - {type: "java", image: "11", PREFIX: "java", SUFFIX: "", context: "./java"}
          - {type: "java", image: "14", PREFIX: "java", SUFFIX: "", context: "./java"}
          - {type: "java", image: "15", PREFIX: "java", SUFFIX: "", context: "./java"}
          - {type: "java", image: "16", PREFIX: "java", SUFFIX: "", context: "./java"}

          - {type: "node", image: "12", PREFIX: "node", SUFFIX: "", context: "./node"}
          - {type: "node", image: "14", PREFIX: "node", SUFFIX: "", context: "./node"}
          - {type: "node", image: "15", PREFIX: "node", SUFFIX: "", context: "./node"}
          - {type: "node", image: "16", PREFIX: "node", SUFFIX: "", context: "./node"}

          - {type: "python", image: "3.7", PREFIX: "python", SUFFIX: "", context: "./python"}
          - {type: "python", image: "3.8", PREFIX: "python", SUFFIX: "", context: "./python"}
          - {type: "python", image: "3.9", PREFIX: "python", SUFFIX: "", context: "./python"}

    steps:
      - name: Code Checkout
        uses: actions/checkout@v2

#      - name: Set up QEMU
#        uses: docker/setup-qemu-action@v1

      - name: Install buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: v0.5.1
          buildkitd-flags: --debug

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Login to Quay
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: matthewp
          password: ${{ secrets.QUAY_SECRET }}

      - name: Login to Private Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: ./${{ matrix.image.context }}
          file: ./${{ matrix.image.type }}/${{ matrix.image.image }}/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/matthewpi/images:${{ matrix.image.PREFIX }}${{ matrix.image.image }}${{ matrix.image.SUFFIX }}
            quay.io/matthewp/pterodactyl:${{ matrix.image.PREFIX }}${{ matrix.image.image }}${{ matrix.image.SUFFIX }}
            ${{ secrets.REGISTRY }}/pterodactyl:${{ matrix.image.PREFIX }}${{ matrix.image.image }}${{ matrix.image.SUFFIX }}
