name: Docker

on:
  push:
    branches:
      - master

jobs:
  push:
    name: Push
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false

      matrix:
        type:
          - "games"
          - "generic"
          - "go"
          - "installers"
          - "java"
          - "node"
          - "python"
        image:
          - "alpine"
          - "fivem"
          - "1.14"
          - "1.15"
          - "1.16"
          - "7"
          - "8"
          - "9"
          - "10"
          - "11"
          - "12"
          - "13"
          - "14"
          - "15"
          - "16"
          - "12"
          - "14"
          - "15"
          - "16"
          - "3.7"
          - "3.8"
          - "3.9"
          - "satisfactory"
          - "source"

        exclude:
          - type: "games"
            image:
              - "alpine"
              - "fivem"
              - "1.14"
              - "1.15"
              - "1.16"
              - "7"
              - "8"
              - "9"
              - "10"
              - "11"
              - "12"
              - "13"
              - "14"
              - "15"
              - "16"
              - "12"
              - "14"
              - "15"
              - "16"
              - "3.7"
              - "3.8"
              - "3.9"
              - "satisfactory"
              - "source"
          - type: "generic"
            image:
              - "alpine"
              - "fivem"
              - "1.14"
              - "1.15"
              - "1.16"
              - "7"
              - "8"
              - "9"
              - "10"
              - "11"
              - "12"
              - "13"
              - "14"
              - "15"
              - "16"
              - "12"
              - "14"
              - "15"
              - "16"
              - "3.7"
              - "3.8"
              - "3.9"
              - "satisfactory"
              - "source"
          - type: "go"
            image:
              - "alpine"
              - "fivem"
              - "1.14"
              - "1.15"
              - "1.16"
              - "7"
              - "8"
              - "9"
              - "10"
              - "11"
              - "12"
              - "13"
              - "14"
              - "15"
              - "16"
              - "12"
              - "14"
              - "15"
              - "16"
              - "3.7"
              - "3.8"
              - "3.9"
              - "satisfactory"
              - "source"
          - type: "installers"
            image:
              - "alpine"
              - "fivem"
              - "1.14"
              - "1.15"
              - "1.16"
              - "7"
              - "8"
              - "9"
              - "10"
              - "11"
              - "12"
              - "13"
              - "14"
              - "15"
              - "16"
              - "12"
              - "14"
              - "15"
              - "16"
              - "3.7"
              - "3.8"
              - "3.9"
              - "satisfactory"
              - "source"
          - type: "java"
            image:
              - "alpine"
              - "fivem"
              - "1.14"
              - "1.15"
              - "1.16"
              - "7"
              - "8"
              - "9"
              - "10"
              - "11"
              - "12"
              - "13"
              - "14"
              - "15"
              - "16"
              - "12"
              - "14"
              - "15"
              - "16"
              - "3.7"
              - "3.8"
              - "3.9"
              - "satisfactory"
              - "source"
          - type: "node"
            image:
              - "alpine"
              - "fivem"
              - "1.14"
              - "1.15"
              - "1.16"
              - "7"
              - "8"
              - "9"
              - "10"
              - "11"
              - "12"
              - "13"
              - "14"
              - "15"
              - "16"
              - "12"
              - "14"
              - "15"
              - "16"
              - "3.7"
              - "3.8"
              - "3.9"
              - "satisfactory"
              - "source"
          - type: "python"
            image:
              - "alpine"
              - "fivem"
              - "1.14"
              - "1.15"
              - "1.16"
              - "7"
              - "8"
              - "9"
              - "10"
              - "11"
              - "12"
              - "13"
              - "14"
              - "15"
              - "16"
              - "12"
              - "14"
              - "15"
              - "16"
              - "3.7"
              - "3.8"
              - "3.9"
              - "satisfactory"
              - "source"

        include:
          - type: "games"
            IMAGE_PREFIX: ""
            IMAGE_SUFFIX: ""
            image:
              - "fivem"
              - "satisfactory"
              - "source"

          - type: "generic"
            IMAGE_PREFIX: ""
            IMAGE_SUFFIX: ""
            image:
              - "alpine"

          - type: "go"
            IMAGE_PREFIX: "go"
            IMAGE_SUFFIX: ""
            image:
              - "1.14"
              - "1.15"
              - "1.16"

          - type: "installers"
            IMAGE_PREFIX: ""
            IMAGE_SUFFIX: "-install"
            image:
              - "alpine"
              - "source"

          - type: "java"
            IMAGE_PREFIX: "java"
            IMAGE_SUFFIX: ""
            image:
              - "7"
              - "8"
              - "9"
              - "10"
              - "11"
              - "12"
              - "13"
              - "14"
              - "15"
              - "16"

          - type: "node"
            IMAGE_PREFIX: "node"
            IMAGE_SUFFIX: ""
            image:
              - "12"
              - "14"
              - "15"
              - "16"

          - type: "python"
            IMAGE_PREFIX: "python"
            IMAGE_SUFFIX: ""
            image:
              - "3.7"
              - "3.8"
              - "3.9"

    steps:
      - name: Code Checkout
        uses: actions/checkout@v2

#      - name: Set up QEMU
#        uses: docker/setup-qemu-action@v1

      - name: Install buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: v0.5.1
          buildkitd-flags: --debug

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Login to Quay
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: matthewp
          password: ${{ secrets.QUAY_SECRET }}

      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: ./${{ matrix.type }}/${{ matrix.image }}
          file: ./${{ matrix.type }}/${{ matrix.image }}/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/matthewpi/images:${{ matrix.IMAGE_PREFIX }}${{ matrix.image }}${{ matrix.IMAGE_SUFFIX }}
            quay.io/matthewp/pterodactyl:${{ matrix.IMAGE_PREFIX }}${{ matrix.image }}${{ matrix.IMAGE_SUFFIX }}
